### ISSUE TITLE
how to use the directive bind?

### ISSUE THREAD

**Issue by roggc** [vuejs/jsx#103]
I am trying to use directive v-bind with jxs but I do not know how.

**Comment by LinusBorg** [comment]
JSX has no directives. you use JSX syntax:

```javascript
<my-element-or-component someProp={this.myLocalData} />
```

**Comment by Aaron-Pool** [comment]
Or, if you're attempting to bind a full object, like in the case of `v-bind="this.$attrs"`, you can use the spread property, like so:

```jsx
<my-element-or-component {...{ attrs: this.myAttributeObject }} />
```
