### ISSUE TITLE
Dynamic components

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/jsx#104]
I'm trying to do this syntax of Vue:
```vue
<component is="MyComponent" my-prop="1' />
```
in JSX:
```jsx
<component is={MyComponent} my-prop={1} />
```

But it doesn't seem to work out of the box...

I looked and looked online, but I can't find a good guide or explanation on this anywhere... If anyone has some advice on how to achieve this, that would be awesome! 😎 

related material (i didn't understand the solution to any of these)
- https://github.com/vuejs/vue/issues/8966
- https://github.com/wonderful-panda/vue-tsx-support/issues/29
- https://github.com/wonderful-panda/vue-tsx-support/issues/30
- https://github.com/vuejs/babel-plugin-transform-vue-jsx#component-tip

**Comment by LinusBorg** [comment]
In JSX, uppercase Tag names are interpreted as variables.


```javascript

import MyComponent from 'my-component.vue'

// ... 

<MyComponent my-prop={1} />
```

So there's no need/quivalent for the `is` prop as JSX has its own way of handling this. To make it dynamic:

```javascript
render(h) {
  const DynamicComponent = // however you determine the component dynamically

  return <DynamicComponent />
}


```

**Comment by mesqueeb** [comment]
@LinusBorg Thanks for your detailed explanation. I'm still a bit confused.

What I was trying to do is something similar to this.

Now I have:
```js
render () {
    let myComponent
    switch (this.$props.myId) {
        case 'someId':
            myComponent = <OneComponent {...myComponentProps} />
            break
        case 'anotherId':
            myComponent = <AnotherComponent {...myComponentProps} />
            break
    }
    return <div>{myComponent}</div>
}
```
I wanted to have something more like:
```js
function getComponentById (id) {
    return myImportedComponents[id]
}
render () {
    const myComponent = <component is={getComponentById(this.$props.myId)} {...myComponentProps} />
    return <div>{myComponent}</div>
}
```
The reason is that my switch function is rather complex, and I want to offload this to another file.

In this case, do you have any advice for my case how to do this better in JSX?
All the best regards,
-Luca

**Comment by LinusBorg** [comment]
```javascript
function getComponentById (id) {
    return myImportedComponents[id]
}
render () {
    // uppercase name is important.
    const Component = getComponentById(this.$props.myId)

    const myComponent =<Component {...myComponentProps} />

    return <div>{myComponent}</div>
}

```

**Comment by mesqueeb** [comment]
@LinusBorg Thank you so much! I finally understand this now.

There are really not enough guides on this I believe... Look it up on Google, there's hardly any info on this anywhere. 😄 

You helped me understand it much better!!! 🙇🏼‍♂️

**Comment by alecmarcus** [comment]
While the above works for dynamically creating components on initial render, I can't seem to find a way to map a dynamic component to a computed value, such that the component updates along with the value. (While using the composition api)

I've been able to do it by storing the component in a `let` and mutating the variable directly in a `watchEffect` hook, but that's circumventing the requirement I think.

## Example code
`layout.tsx`
```TSX
import { defineComponent, computed, watchEffect } from "@vue/composition-api";
import Default from "./Default";
import Test from "./Test";

const Layout = defineComponent({
  name: "Layout",
  setup(props, { root }) {
    const layoutMappings = new Map([
      ["Home", Default],
      ["Login", Test],
    ]);

    const routeName = computed(() => root.$route.name);

    const Layout = layoutMappings.get(root.$route.name || "Home") || Default;

    watchEffect(() =>
      console.log(routeName.value, " I update on route changes")
    );

    watchEffect(() => console.log(Layout, " I do not"));

    return () => (
      <Layout key={routeName.value}>
          <router-view />
      </Layout>
    );
  },
});

export default Layout;
```

**Comment by sethidden** [comment]
What if you want to mix JSX with regular Vue <component :is=""> ?

```
<template>
  <div>
    <component :is="myComponent"/>
  </div>
</template>
<script>
  export default {
    computed: {
      myComponent() {
        return <div>hello</div>
      }
    }
  }
</script>
```

This won't work, but component :is="{ render: myComponent }" will
