### ISSUE TITLE
Error: Cannot find module '@vue/babel-preset-jsx' from <Project Path>

### ISSUE THREAD

**Issue by brennj** [vuejs/jsx#12]
**Issue**
Hi there, it seems the `'@vue/babel-preset-jsx'` doesn't ship the built code on `npm`/`yarn` install. I started up a fresh default config project with the latest Vue CLI and followed the instructions on this projects read me and was met with the titles error. 

**Repro steps** _Assuming latest vue-cli 3 is installed as global package_
1. `cd ~/`
2. `vue create jsx && cd jsx`
3. Select default config.
4. `yarn add @vue/babel-preset-jsx @vue/babel-helper-vue-jsx-merge-props --dev`
5. Add `'@vue/babel-preset-jsx'` to `babel.config.js`.
6. `yarn serve`

You will see failure.

**How I got it working locally**
1. `yarn add @babel/core`.
2. `yarn add babel-loader`.
3. `cd node_modules/@vue-babel-preset-jsx`,
4. `yarn && yarn build` in `@vue/babel-preset-jsx`.
5.  `cd ../../../ && yarn serve`

Thanks so much for the project, I've been trying to figure out how to get React like functional components in Vue because it's something I really miss using in my day job. So thank you so much!

**Comment by nickmessing** [comment]
Sorry guys, working on it :sweat_smile:

**Comment by DM2489** [comment]
+1, this is needed! :)

**Comment by DM2489** [comment]
Actually, would anyone who has already built this up in Yarn mind sharing the dist?

I don't use Yarn at the moment, and It would be a big help if someone could do this until this is officially released.

**Comment by daniele-orlando** [comment]
Any news?

**Comment by DM2489** [comment]
No, unfortunately. I ended up installing Yarn and building my own, but this isn't particularly sustainable in multiple team & multiple developer situations.

**Comment by daniele-orlando** [comment]
I moved to [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx).

**Comment by nickmessing** [comment]
This is going to be fixed in next release
