### ISSUE TITLE
Consider adding vue-jsx-hot-loader

### ISSUE THREAD

**Issue by skyrpex** [vuejs/jsx#13]
Hi there!

A log time ago I developed a Webpack loader to enable HMR for Vue components that use JSX (render functions):

```javascript
// component.jsx
export default {
    render(h) {
        return (
            <div>
                <p>Hello</p>
            </div>
        );
    },
};
```

The package is located here: https://github.com/skyrpex/vue-jsx-hot-loader It's been working great so far, so I think it would be nice to officially add it here.

**Comment by nickmessing** [comment]
@yyx990803, @znck, @sodatea, opinions on this? I will test it and if it really works would be great.

**Comment by znck** [comment]
I'm trying to understand how it's different from [vue-loader's hot reloading logic](https://github.com/vuejs/vue-loader/blob/master/lib/codegen/hotReload.js)?

On a side note, hot reloading should be a feature of build tool so vue-loader is the correct place for this feature.

**Comment by nickmessing** [comment]
@znck, if I understand correctly, it's doing the same that vue-loader is doing with templates, but with `render()` methods.

**Comment by skyrpex** [comment]
> I'm trying to understand how it's different from vue-loader's hot reloading logic?

The logic should be the same, just that it works for non `.vue` files (for example, `.jsx` files like the one in the example above, or even `.tsx` files).

Using render functions instead of templates allows the editor of your choice to typehint your variables when rendering.

**Comment by nickmessing** [comment]
Hot-loader should definitely not be a part of babel preset, consider adding it to vue-cli instead.

**Comment by skyrpex** [comment]
Fair enough! Got misleaded by the repo description (`monorepo for Babel / Vue JSX related packages`). It sounds more generic than it actually is 😆

**Comment by skyrpex** [comment]
vue-cli issue: https://github.com/vuejs/vue-cli/issues/3965
