### ISSUE TITLE
jsx中使用vBind绑定$attrs提示指令不存在

### ISSUE THREAD

**Issue by FCX666666** [vuejs/jsx#134]
code: vBind={this.$attrs}
console: Failed to resolve directive: bind

**Comment by FCX666666** [comment]
在jsx中只能这样传递组件未从定义props中的属性吗？

`required = {this.$attrs.required}
 placeholder={this.$attrs.placeholder}
`

**Comment by haoqunjiang** [comment]
```jsx
<my-element-or-component {...{ attrs: this.$attrs }} />
```
