### ISSUE TITLE
为什么对象数组直接输出是undefined？

### ISSUE THREAD

**Issue by xmsz** [vuejs/jsx#135]
```
    const state = reactive({
      awardList: [
        {
          num: 1,
        },
      ],
    });
```
```
<div>
          {state.awardList}
          {state.awardList[0].num}
          {JSON.stringify(state.awardList)}
</div>
```

```
          {state.awardList} => undefined
          {state.awardList[0].num} =>  1
          {JSON.stringify(state.awardList)} => "[{num:1}]"
```

![image](https://user-images.githubusercontent.com/5879146/79407312-c5181580-7fcb-11ea-8324-1ae8ced032e5.png)

It works fine with number's array or string's array
```
    const state = reactive({
      awardList: [0],
    });
```

> can you provide a repro, please?

https://github.com/xmsz/vue-jsx-object-array-returns-undefined

```
npm run serve
```

**Comment by haoqunjiang** [comment]
```jsx
<div>
  {state.awardList}
  {state.awardList[0].num}
  {JSON.stringify(state.awardList)}
</div>
```

这样写的话，此处三个表达式是被当成 `div` 的 children 处理的，关于 children 接收什么类型可以看文档：https://cn.vuejs.org/v2/guide/render-function.html#createElement-%E5%8F%82%E6%95%B0
只能是字符串或者 VNode 类型。
这里是没有做 toString 操作的。
具体实现看 https://github.com/vuejs/vue/blob/dev/src/core/vdom/helpers/normalize-children.js

总之，传了错误的参数类型，结果肯定是未定义的。

**Comment by xmsz** [comment]
> ```js-jsx
> <div>
>   {state.awardList}
>   {state.awardList[0].num}
>   {JSON.stringify(state.awardList)}
> </div>
> ```
> 
> 这样写的话，此处三个表达式是被当成 `div` 的 children 处理的，关于 children 接收什么类型可以看文档：https://cn.vuejs.org/v2/guide/render-function.html#createElement-%E5%8F%82%E6%95%B0
> 只能是字符串或者 VNode 类型。
> 这里是没有做 toString 操作的。
> 具体实现看 https://github.com/vuejs/vue/blob/dev/src/core/vdom/helpers/normalize-children.js
> 
> 总之，传了错误的参数类型，结果肯定是未定义的。

这个是我自己的问题，今天我又试了一下，没有问题了。

昨天遇到的是我想把awardList这个对象数组传递到一个组件。发现组件内没有成功渲染。然后就直接{awardList}输出，结果是undefined。

然后就想错了方向，以为这个是因为awardList undefined造成不能渲染。
