### ISSUE TITLE
Is staticClass no longer supported ?

### ISSUE THREAD

**Issue by wonderful-panda** [vuejs/jsx#14]
Now, staticClass does not work.

## Reproduction

Input code:
```javascript
<div staticClass="foo" />;
```

Transpiled by `babel-plugin-transform-vue-jsx` (works):

```javascript
h("div", { staticClass: "foo" });
```

Transpiled by `@vue/babel-plugin-transform-vue-jsx` (does not work):

```javascript
h("div", {
  "attrs": {
    "staticClass": "foo"
  }
});
```

**Comment by yyx990803** [comment]
Looks like a bug. It should be top level.
