### ISSUE TITLE
Uncaught (in promise) TypeError: h is not a function

### ISSUE THREAD

**Issue by tomasgil123** [vuejs/jsx#182]
I made a test component with jsx:
```
//test.jsx
import { defineComponent } from "vue";

export default defineComponent({
  render() {
    return <div>Parent</div>;
  }
});
```
When I try to use it the app crashes with the following error:
![image](https://user-images.githubusercontent.com/14185059/108607810-69fc3f80-73a1-11eb-86f8-4e456de197b1.png)

**Comment by haoqunjiang** [comment]
This preset only supports Vue 2 JSX.
For Vue 3 projects please use https://github.com/vuejs/jsx-next
