### ISSUE TITLE
Conversation: Support & future curators

### ISSUE THREAD

**Issue by DM2489** [vuejs/jsx#19]
First of all, thanks to @nickmessing for the work here on Vue JSX and this Monorepo. The following is not a compliant in any way, but with reference to https://github.com/vuejs/jsx/issues/2, I'm just a little concerned around the lack of a roadmap and the development direction, and want to spark a discussion of what could be done to help take things forward.

As a little background, one of the key reasons we chose to use Vue over React in my organisation was the ability to still use JSX, and with recently having to upgrade to Node 10, NPM 6 and Babel 7 (for various maintainability & security reasons), this package is the only way I can find to restore some JSX functionality to my organisation's work, using these dependencies.

I know that this package is 0.1.0, and hasn't yet matured. Is there a way that we, as a community can help to get this package to where it needs to be? Obviously we can report issues and submit PR's for how we believe things should be fixed, but with no understanding of design decisions, or the intended direction of development, it's a little difficult to do things in accordance with the wishes of the maintainer.

Importantly, there is a big reliance here on @nickmessing to do all the merging and upversioning. Would it be possible to get more people from the Vue team, or even more people with an interest in JSX, as curators for this repository in the future, to help accelerate the development and maturation of this repo?

Again, this isn't a complaint or a criticism, I really appreciate @nickmessing's work here; I just want to spark conversations to help move this forward.

**Comment by yyx990803** [comment]
I will likely take some time before holidays to at least get things sorted out here.

**Comment by DM2489** [comment]
Thanks @yyx990803, that would be most appreciated.
