### ISSUE TITLE
Is there a roadmap for this?

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/jsx#2]
I saw a comment about this repo made a few months ago here: https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11

But there isn't anything here right now. Any update on where this repo is headed?

**Comment by nickmessing** [comment]
@Aaron-Pool, you can monitor progress on nickmessing/jsx right now, working on new v-model and event modifiers for now

**Comment by Aaron-Pool** [comment]
Thanks! 👍

**Comment by DM2489** [comment]
@nickmessing Appears that this repository is more up to date than nickmessing/jsx. Keeping a close eye on this project, but it would be nice to have a bit of an update on this project and what is left for v1.

Looks good so far though! ooking forward to moving away from the individual packages.
