### ISSUE TITLE
无法在vue2.7的setup中使用jsx

### ISSUE THREAD

**Issue by wehuss** [vuejs/jsx#287]
插件版本:

- "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1"
- "@vue/babel-preset-jsx": "^1.3.0"

vue版本:2.7.4

babel配置如下:
```
// babel.config.js
module.exports = {
  presets: [
    ['@vue/babel-preset-jsx', { compositionAPI: true,injectH:false }],
  ],
  plugins:[['@babel/plugin-transform-typescript', { isTSX: true }]],
}
// index.tsx
import { defineComponent } from 'vue'

export default defineComponent({
  setup() {
    return () => <div>testtttttttt</div>
  },
})
```
错误信息:
![image](https://user-images.githubusercontent.com/48681136/178886287-04c6ccab-552d-4a35-8127-f64d4364140f.png)

**Comment by wehuss** [comment]
暂时先这样解决了
![image](https://user-images.githubusercontent.com/48681136/178889906-bf78698a-0d8c-4877-afbf-81fb3368a3de.png)

**Comment by jetBn** [comment]
能获取到ref 吗？

**Comment by jetBn** [comment]
使用了jsx  setup 中返回元素 使用ref获取 不到dom啥原因？

**Comment by wehuss** [comment]
@vue/cli-plugin-babel版本问题

**Comment by emosheeep** [comment]
具体要用哪个版本呀

**Comment by wehuss** [comment]
> 
vue2.7中直接用最新版即可。
但如果在babel中使用了`@vue/cli-plugin-babel/preset`且`@vue/cli-plugin-babel`版本低于小于5.0.8的话则需要将`@vue/cli-plugin-babel/preset`配置中的jsx选项关闭
![image](https://user-images.githubusercontent.com/48681136/182068539-61f145ca-6f91-4372-8c9b-53a3e712c7e7.png)

**Comment by wehuss** [comment]
> 具体要用哪个版本呀

vue2.7中直接用最新版即可。
但如果在babel中使用了`@vue/cli-plugin-babel/preset`且`@vue/cli-plugin-babel`版本低于小于5.0.8的话则需要将`@vue/cli-plugin-babel/preset`配置中的jsx选项关闭
![image](https://user-images.githubusercontent.com/48681136/182068622-64573d6f-b076-42d8-aea6-dc8b984e74c7.png)

**Comment by emosheeep** [comment]
> > 具体要用哪个版本呀
> 
> vue2.7中直接用最新版即可。 但如果在babel中使用了`@vue/cli-plugin-babel/preset`且`@vue/cli-plugin-babel`版本低于小于5.0.8的话则需要将`@vue/cli-plugin-babel/preset`配置中的jsx选项关闭 ![image](https://user-images.githubusercontent.com/48681136/182068622-64573d6f-b076-42d8-aea6-dc8b984e74c7.png)

绝了，确实是这样，然后我们工作环境在pnpm的monorepo中，即便更新`@vue/cli-plugin-babel`插件到5.0.8版本可能
也会有些奇怪的问题，索性像你这样，自己安装`@vue/babel-preset-jsx`到1.3.1然后手动配置compositionAPI。谢了老哥。
<img width="694" alt="截屏2022-08-01 12 12 46" src="https://user-images.githubusercontent.com/31957758/182070808-e0692388-1554-4171-8ae8-089b7f4e672f.png">

**Comment by agileago** [comment]
为啥关闭issue了？有同样问题

**Comment by wehuss** [comment]
> 为啥关闭issue了？有同样问题
看我上面的回复

**Comment by wehuss** [comment]
> 为啥关闭issue了？有同样问题

看我上面的回复

**Comment by kunl** [comment]
```
    "vite": "^3.0.0"
  "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
    "@vue/babel-preset-jsx": "^1.3.1",  
    "@vitejs/plugin-vue2": "^1.1.2",
    "@vue/cli-plugin-babel": "^5.0.8",

presets: [
    ['@vue/cli-plugin-babel/preset', { jsx: false }],
    ['@vue/babel-preset-jsx', { compositionAPI: true }]
  ],
```

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/2870324/182379731-1acfb8ab-3aee-4787-8fdb-1f24105790fb.png">
并没有解决啊

**Comment by emosheeep** [comment]
> ```
>  "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
>    "@vue/babel-preset-jsx": "^1.3.1",  
>    "@vitejs/plugin-vue2": "^1.1.2",
>    "@vue/cli-plugin-babel": "^5.0.8",
> 
> presets: [
>    ['@vue/cli-plugin-babel/preset', { jsx: false }],
>    ['@vue/babel-preset-jsx', { compositionAPI: true }]
>  ],
> ```
> 
> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/2870324/182379731-1acfb8ab-3aee-4787-8fdb-1f24105790fb.png">
> 
> 并没有解决啊

我们的问题不一样，你这个是另外的问题了，话说你都用vite了，还用啥babel，直接用@vitejs/plugin-vue2-jsx就可以了哇

**Comment by kunl** [comment]
@1446445040   我这是  vite 开发， cli 打包。明天我再试试吧。



> > ```
> >  "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
> >    "@vue/babel-preset-jsx": "^1.3.1",  
> >    "@vitejs/plugin-vue2": "^1.1.2",
> >    "@vue/cli-plugin-babel": "^5.0.8",
> > 
> > presets: [
> >    ['@vue/cli-plugin-babel/preset', { jsx: false }],
> >    ['@vue/babel-preset-jsx', { compositionAPI: true }]
> >  ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1124" src="https://user-images.githubusercontent.com/2870324/182379731-1acfb8ab-3aee-4787-8fdb-1f24105790fb.png">
> > 并没有解决啊
> 
> 我们的问题不一样，你这个是另外的问题了，话说你都用vite了，还用啥babel，直接用@vitejs/plugin-vue2-jsx就可以了哇

**Comment by xiangtaot** [comment]
> @1446445040 我这是vite开发，cli打包。明天我再试吧。
> 
> > > ```
> > >  "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
> > >    "@vue/babel-preset-jsx": "^1.3.1",  
> > >    "@vitejs/plugin-vue2": "^1.1.2",
> > >    "@vue/cli-plugin-babel": "^5.0.8",
> > > 
> > > presets: [
> > >    ['@vue/cli-plugin-babel/preset', { jsx: false }],
> > >    ['@vue/babel-preset-jsx', { compositionAPI: true }]
> > >  ],
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="图像" width="1124" src="https://user-images.githubusercontent.com/2870324/182379731-1acfb8ab-3aee-4787-8fdb-1f24105790fb.png">
> > > 并没有解决办法啊
> > 
> > 
> > 我们的问题不一样，你这个是另外的问题了，说你都用vite了，还用啥babel，直接接用@vitejs/plugin-vue2-jsx就可以了哇



> ```
>    "vite": "^3.0.0"
>  "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
>    "@vue/babel-preset-jsx": "^1.3.1",  
>    "@vitejs/plugin-vue2": "^1.1.2",
>    "@vue/cli-plugin-babel": "^5.0.8",
> 
> presets: [
>    ['@vue/cli-plugin-babel/preset', { jsx: false }],
>    ['@vue/babel-preset-jsx', { compositionAPI: true }]
>  ],
> ```
> 
> <img alt="图像" width="1124" src="https://user-images.githubusercontent.com/2870324/182379731-1acfb8ab-3aee-4787-8fdb-1f24105790fb.png">
> 
> 并没有解决办法啊vite不是有专门解析jsx的插件@vitejs/plugin-vue-jsx

**Comment by Dinert** [comment]
看一下这个能不能帮到你们：https://juejin.cn/post/7342420969875210291

**Comment by zhao-yi-fan** [comment]
大佬们，有见过这个报错吗？使用的vue 2.7.16 vue-cli4 用的setup中写jsx语法
Cannot read properties of undefined (reading 'body')
```
<template>
  <Form
    ref="form"
    v-model="dialogFormData"
    :formItemList="formItemList()"
  />
</template>
<script setup>
import {ref} from 'vue'

const dialogFormData = ref({})

const formItemList = () => {
  return [
    {
      prop: 'xxx',
      label: 'xxx',
      render: () => {
        return (
          <Select
            vModel={dialogFormData.value.countryCode}
            on={{
              change: Change,
            }}
          ></Select>
        )
      },
    }
 ]
}

const Change = () => {}
</script>
```


```
    "@vue/babel-helper-vue-jsx-merge-props": "^1.4.0",
    "@vue/babel-preset-jsx": "^1.4.0",
    "@vue/cli-plugin-babel": "^4.5.19",
    "@vue/cli-plugin-eslint": "^4.5.19",
    "@vue/cli-plugin-router": "^4.5.19",
    "@vue/cli-plugin-vuex": "^4.5.19",
    "@vue/cli-service": "^4.5.19",
    "vue": "^2.7.16",
`````
babel.config.js
```
presets: [
    ['@vue/cli-plugin-babel/preset', { jsx: false }],
    ['@vue/babel-preset-jsx', { compositionAPI: true }],
  ],
```
<img width="1021" alt="image" src="https://github.com/vuejs/jsx-vue2/assets/39518615/eef968ee-c13c-4c97-ad65-124cf70216f1">

**Comment by guohuihot** [comment]
> 大佬们，有见过这个报错吗？使用的vue 2.7.16 vue-cli4 用的setup中写jsx语法 Cannot read properties of undefined (reading 'body')
> 
> ```
> <template>
>   <Form
>     ref="form"
>     v-model="dialogFormData"
>     :formItemList="formItemList()"
>   />
> </template>
> <script setup>
> import {ref} from 'vue'
> 
> const dialogFormData = ref({})
> 
> const formItemList = () => {
>   return [
>     {
>       prop: 'xxx',
>       label: 'xxx',
>       render: () => {
>         return (
>           <Select
>             vModel={dialogFormData.value.countryCode}
>             on={{
>               change: Change,
>             }}
>           ></Select>
>         )
>       },
>     }
>  ]
> }
> 
> const Change = () => {}
> </script>
> ```
> 
> ```
>     "@vue/babel-helper-vue-jsx-merge-props": "^1.4.0",
>     "@vue/babel-preset-jsx": "^1.4.0",
>     "@vue/cli-plugin-babel": "^4.5.19",
>     "@vue/cli-plugin-eslint": "^4.5.19",
>     "@vue/cli-plugin-router": "^4.5.19",
>     "@vue/cli-plugin-vuex": "^4.5.19",
>     "@vue/cli-service": "^4.5.19",
>     "vue": "^2.7.16",
> ```
> 
> babel.config.js
> 
> ```
> presets: [
>     ['@vue/cli-plugin-babel/preset', { jsx: false }],
>     ['@vue/babel-preset-jsx', { compositionAPI: true }],
>   ],
> ```
> 
> <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/39518615/326741252-eef968ee-c13c-4c97-ad65-124cf70216f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NTg0MTEsIm5iZiI6MTcxNDk1ODExMSwicGF0aCI6Ii8zOTUxODYxNS8zMjY3NDEyNTItZWVmOTY4ZWUtYzEzYy00Yzk3LWFkNjUtMTI0Y2Y3MDIxNmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAxMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzE4ZjcwN2JlNTFhNWI4YmYwYzZiNzY1NTczMTEwMWRkMTE4NTEwZTc3ZjcyYmJmNjBmMzAyMjJlYTI1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGHSLe89qmNZp9Wq4-MaBIEXP9BefCjEIZxTIrWuONw">

不要用vModel，改为value + onInput

**Comment by zhao-yi-fan** [comment]
> > 大佬们，有见过这个报错吗？使用的vue 2.7.16 vue-cli4 用的setup中写jsx语法 Cannot read properties of undefined (reading 'body')
> > ```
> > <template>
> >   <Form
> >     ref="form"
> >     v-model="dialogFormData"
> >     :formItemList="formItemList()"
> >   />
> > </template>
> > <script setup>
> > import {ref} from 'vue'
> > 
> > const dialogFormData = ref({})
> > 
> > const formItemList = () => {
> >   return [
> >     {
> >       prop: 'xxx',
> >       label: 'xxx',
> >       render: () => {
> >         return (
> >           <Select
> >             vModel={dialogFormData.value.countryCode}
> >             on={{
> >               change: Change,
> >             }}
> >           ></Select>
> >         )
> >       },
> >     }
> >  ]
> > }
> > 
> > const Change = () => {}
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >     "@vue/babel-helper-vue-jsx-merge-props": "^1.4.0",
> >     "@vue/babel-preset-jsx": "^1.4.0",
> >     "@vue/cli-plugin-babel": "^4.5.19",
> >     "@vue/cli-plugin-eslint": "^4.5.19",
> >     "@vue/cli-plugin-router": "^4.5.19",
> >     "@vue/cli-plugin-vuex": "^4.5.19",
> >     "@vue/cli-service": "^4.5.19",
> >     "vue": "^2.7.16",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > babel.config.js
> > ```
> > presets: [
> >     ['@vue/cli-plugin-babel/preset', { jsx: false }],
> >     ['@vue/babel-preset-jsx', { compositionAPI: true }],
> >   ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/39518615/326741252-eef968ee-c13c-4c97-ad65-124cf70216f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NTg0MTEsIm5iZiI6MTcxNDk1ODExMSwicGF0aCI6Ii8zOTUxODYxNS8zMjY3NDEyNTItZWVmOTY4ZWUtYzEzYy00Yzk3LWFkNjUtMTI0Y2Y3MDIxNmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAxMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzE4ZjcwN2JlNTFhNWI4YmYwYzZiNzY1NTczMTEwMWRkMTE4NTEwZTc3ZjcyYmJmNjBmMzAyMjJlYTI1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGHSLe89qmNZp9Wq4-MaBIEXP9BefCjEIZxTIrWuONw">
> 
> 不要用vModel，改为value + onInput

大佬牛啊👍，确实因为是vModel的问题，拆成value input就可以了。困扰了我一个星期了，还以为是配置的问题。
