### ISSUE TITLE
i want to know that how to use v-slot instead slot directive in jsx-vue2 

### ISSUE THREAD

**Issue by Yh1404** [vuejs/jsx#304]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/39335644/229451198-0a2610f2-2bea-4d6f-a7d3-8c78be028c31.png">

**Comment by Yh1404** [comment]
this way has a problem that the table are not rerender when i update array for the table header, and the $forceUpdate method is not working either

**Comment by Yh1404** [comment]
i found a solution just using v-slot，but i do not know the grammar of v-slot in jsx-vue2

**Comment by kikyouink** [comment]
我在这里读不到row，兄弟你能读到嘛

**Comment by Yh1404** [comment]
> 我在这里读不到row，兄弟你能读到嘛
试着检查你的slot或着el-table用法
