### ISSUE TITLE
在 Rspack 中无法正常工作

### ISSUE THREAD

**Issue by Y80** [vuejs/jsx#311]
## 问题描述
`.vue` 组件在 `setup() {}` 中返回了 JSX 组件，例如：
```JavaScript
defineComponet({
  setup() {
    return () => <div>ok</div>
  }
})
```
经过插件编译之后，始终 `const h = this.$createElement`

![image](https://github.com/vuejs/jsx-vue2/assets/40132433/ffdc0ab9-9b50-4b57-8561-3724d1d6ad61)

## Rspack 配置

<img width="557" alt="image" src="https://github.com/vuejs/jsx-vue2/assets/40132433/7446536c-78d8-45e4-8bc5-935f20c032b5">
 
## 期望
如果检测到是在 `setup()` 中，使用 `getCurrentInstance()?.proxy` 替换 `this`。或者使用 `import { h } from 'vue'`。

## 其他
我猜应该是插件 @vue/babel-sugar-composition-api-render-instance 在 Rspack 中失效了。（Rspack 没有兼容其中某些 API？）
使用 Vite 时可以正常运行，`h` 是从 `vue` 依赖中导入的。

**Comment by yejinjian** [comment]
解决了吗？

**Comment by Y80** [comment]
> 解决了吗？

好像解决了。应该是 Rspack 后来更新无意间修复了这个 BUG。

不过使用 `.tsx / .jsx` 的话是铁定没这个问题的。

![image](https://github.com/vuejs/jsx-vue2/assets/40132433/ee911acb-3f3a-40d4-aca7-e81b4153bbb8)
