### ISSUE TITLE
when jsx has the "props" attribute it will take an error

### ISSUE THREAD

**Issue by nailfar** [vuejs/jsx#32]
![image](https://user-images.githubusercontent.com/12581226/50509431-c6fd5300-0ac0-11e9-96aa-15912f704b7d.png)
![image](https://user-images.githubusercontent.com/12581226/50509445-d11f5180-0ac0-11e9-86f9-b9c7efde1475.png)
node_modules\@vue\babel-plugin-transform-vue-jsx\dist\plugin.js
![image](https://user-images.githubusercontent.com/12581226/50509462-e2685e00-0ac0-11e9-90a4-9fd09790ec79.png)

**Comment by nickmessing** [comment]
Yes, at the moment you can use:
`props-children="children"` and `props-label="label"`
I will add ability to pass root attributes like this in the next build
