### ISSUE TITLE
Need jsx-control-statements support.

### ISSUE THREAD

**Issue by xiaozs** [vuejs/jsx#35]

**Comment by nickmessing** [comment]
You can use it, should be completely compatible with Vue JSX

**Comment by xiaozs** [comment]
@nickmessing 
No, it just work with jsxElements don't in render function.

**Comment by nickmessing** [comment]
@xiaozs, can you please create a reproduction that doesn't work?

**Comment by xiaozs** [comment]
@nickmessing 
https://github.com/xiaozs/vmodelbug.git

**Comment by shortstuffsushi** [comment]
@xiaozs could you explain what in the repository you linked you see as a bug in this codebase? I assume you're talking about the the [`<For>`](https://github.com/xiaozs/vmodelbug/blob/1799abeaabf20a39e35543a5747c1dc1a27e3379/src/page.vue#L11) elements that you made?

I think you may be misunderstanding JSX in general, as opposed to this being a problem with this Vue plugin. Have a look at [this StackOverflow response](https://stackoverflow.com/a/22877110/1252541), that may help.

The gist is that to loop, you might instead do something like this

```
render: function () {
    return (
        <table>
            // For
            {
                this.someArray.map(function(obj) {
                    <tr><td>{ obj.property }</td></tr>
                })
            }

            // if
           {
                !this.someArray.length &&
                <tr><td>No content</td></tr>
           }
        </table>
    );
}
```

Does this make sense? Does that answer the question you have?

**Comment by donnysim** [comment]
@shortstuffsushi he's using https://github.com/AlexGilleran/jsx-control-statements which adds If, For etc support as control statements, I've thought about trying it but haven't yet. If this doesn't work with vue jsx then that answers my question of trying.

**Comment by shortstuffsushi** [comment]
Ah, ok. Wasn't familiar - sorry for making assumptions. It doesn't seem like that library works well with this plugin. The "method For" in the attached example seemed to work, but the "render For" didn't.

**Comment by xiaozs** [comment]
yes，its what i mean，
jsx-control-statements will replace the Ast of Jsx tag like <For> to the Ast of map,
and i have had debugged that the replacements have occurred in the render method。

**Comment by nickmessing** [comment]
Since this is not a part of JSX scope, if you want to support jsx-control-statements you should create a separate project for that or report specific bugs that don't allow it to work with Vue JSX.
