### ISSUE TITLE
Remove whitespace between HTML tags 

### ISSUE THREAD

**Issue by chenjiahan** [vuejs/jsx#37]
Currently the preset will preserve whitespaces between HTML tags by default, can you provide a option like `preserveWhitespace ` in vue-loader, or just remove whitespace between HTML tags like JSX in React?

#### input: 
```html
<div>
  <span>{this.text}</span>
  <span>{this.text}</span>
</div>
```

#### output:
```js
h('div', [
  h('span', [this.text]),
  '\n        ',
  h('span', [this.text])
]);
```

#### expected:
```js
h('div', [
  h('span', [this.text]),
  h('span', [this.text])
]);
```

**Comment by nickmessing** [comment]
Sure, we should replicate React JSX Transform's way of handling whitespaces...

**Comment by chenjiahan** [comment]
😆Thanks！
