### ISSUE TITLE
update:prop doesn't seem to work

### ISSUE THREAD

**Issue by kpilard** [vuejs/jsx#44]
I've tried both suggestions from issue #40 
Unfortunately, neither has worked.

```
<v-data-table onUpdated:pagination={this.updatePagination} />
<v-data-table on-updated:pagination={this.updatePagination} />
```

If i call `this.$listeners` in the `v-data-table` the only registered listener is `update`. It looks like the colon and the attribute are truncated.

**Comment by kpilard** [comment]
@nickmessing Yes that is the syntax we are using at the moment. But the syntax is not really nice.

I don't think it is a vuetify related topic. The pagination property in `<v-data-table />`  supports the `.sync` modifier https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

In classic vue templates the `.sync` is just an shortcut. Similiar to `v-model`. 
```
<v-data-table :pagination.sync="pagination" />
```
is a shortcut of 
```
<v-data-table 
    :pagination="pagination" 
    @update:pagination="pagination => this.pagination = pagination" 
/>
```

It would be nice to have better support for the `.sync` modifier in any form.

**Comment by nickmessing** [comment]
Unfortunately, this will not be supported as part of core JSX, as a distant possibility we might add it as a part of Vue 3 release if we define an RFC for it, feel free to suggest syntax option in rfcs repo: https://github.com/vuejs/rfcs
