### ISSUE TITLE
Transparent wrapper component pattern with JSX

### ISSUE THREAD

**Issue by maoberlehner** [vuejs/jsx#47]
I'm trying to recreate something like this https://zendev.com/2018/05/31/transparent-wrapper-components-in-vue.html with JSX.

```js
// This does not work:
// `[Vue warn]: Failed to resolve directive: on`
export const MyComponent = {
  render() {
    return <div vOn={this.$listeners}>{this.$slots.default}</div>
  }
};
```

This results in `[Vue warn]: Failed to resolve directive: on`.

For now I use render functions instead, but I'd love to use JSX to create transparent wrapper components. Is this already possible and I do something wrong or is this just not supported?

```js
// This works but I'd love to use JSX.
export const MyComponent = {
  render() {
    return h(
      'div',
      { on: this.$listeners },
      this.$slots.default,
    );
  }
};
```

Thanks!

**Comment by yyx990803** [comment]
You can probably do this: `<div {...{ on: this.$listeners }}>`

**Comment by maoberlehner** [comment]
Yes, it works!
Thank you very much for your super fast response!

Should we keep this issue as a feature request or should I close it?

**Comment by nickmessing** [comment]
@maoberlehner, I think the best design would be `<div on={this.$listeners} />`, will check if that works and if it doesn't - will add it.
