### ISSUE TITLE
Support for Fragment wrapper

### ISSUE THREAD

**Issue by privatenumber** [vuejs/jsx#50]
Looking for support for the fragment wrapper syntax: `<>Content</>`

**Comment by Kocal** [comment]
That would be awesome :+1: 

A good use case is for `<template v-if>` that has multiple root:
```vue
<template v-if="n > 4">
  <div>Foo</div>
  <div>Bar</div>
</template>
```

The following code does not work (syntax error):
```jsx
{n > 4 && (
  <div>Foo</div>
  <div>Bar</div>
)}
```

But we can make it works with a fragment:
```jsx
{n > 4 && (
  <>
    <div>Foo</div>
    <div>Bar</div>
  </>
)}
```

**Comment by nickmessing** [comment]
Yes, that will be available in Vue 3, however, right now you can just use old-school arrays:
```js
{n > 4 && [
  <div>Foo</div>,
  <div>Bar</div>,
]}
```

**Comment by Kocal** [comment]
Oh, I totally forgot about this syntax, thanks :)
