### ISSUE TITLE
namespaced syntax (e.g., vOn:click) does not work with tsx

### ISSUE THREAD

**Issue by speigg** [vuejs/jsx#52]
Sadly, typescript does not support namespaced attributes. Periods (e.g.,`vOn.click`) will not work in TSX files either. Only options seem to be `vOn_click` and `vOn-click`.

**Comment by fyAgent** [comment]
i had a similar problem with the difference is syntax is not supported on vscode
![image](https://user-images.githubusercontent.com/31948326/55340314-0760d880-54d7-11e9-9ce9-9f25eb6fed2f.png)

**Comment by nickmessing** [comment]
Unfortunately TSX does not support namespaced attributes, there is no way around so I'm working on a different syntax in http://github.com/nickmessing/vue-tsx/

**Comment by snowyu** [comment]
do not use `vOn:xxx` on typescript, just

```tsx
function handleClick(e) {...};
return <div onClick={handleClick}></div>

// Or 
return <div 
  {...{
    on: {
       ...this.$listener,
      click: handleClick
    }
  }}
></div
```
