### ISSUE TITLE
HOCs not working correctly

### ISSUE THREAD

**Issue by Deviad** [vuejs/jsx#53]
There are a few things that right now do not work

```
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return h(<div>whatever</div>)
}
}
export default Component(Select);
```

Expected output `<div>whatever</div>`, does not print anything.
```
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return h(<div class="whatever"><WrappedComponent/></div>)
}
}
export default Component(Select);
```
Expected output `<div class="whatever">{WrappedComponent contents}</div>`, does not print the enclosing div (`<div class="whatever">`), but only the contents of WrappedComponent.

```
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return h(<WrappedComponent class="whatever"/>)
}
}
export default Component(Select);
```
Does not augment the component with class whatever. I tried also with className and

    return h(<WrappedComponent/>, {class: "whatever"})

**Comment by Aaron-Pool** [comment]
It may be helpful if you study through the `vue/jsx` documentation more thoroughly. `h(<jsxOfAnyKind/>)` is not valid syntax. The purpose of jsx is to avoid the more verbose and hard to read `h(compDefinition, data, children)` syntax. You're mixing the two. Which is going to lead to unexpected results.

What you probably _want_ to return is:

```js
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return <WrappedComponent class="whatever" { ...{ props, listeners } } />;
  }
}
export default Component(Select);
```

Assuming `Select` is a valid component definition. You'll also need to deal with passing children through, if `Select` uses any slotting.

**Comment by nickmessing** [comment]
@Aaron-Pool is right but I will add some more in-depth documentation on HOC

**Comment by Aaron-Pool** [comment]
@nickmessing some direction on the most elegant method to transfer props would also be a welcome addition to the docs.

Like [you can in react](https://zhenyong.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx). It's substantially more complex in vue because in functional properties there are multiple places you need to parse props. There's the `props` field on the `context` object, the `props` field on the `data` field _in_ the the `context` object. And then most fields in `props` exist on `context.data.attrs` as well. It's difficult to know exactly what you need to do to make sure certain props/attributes are consumed by the parent (and not propagated to the child after) and others are available to the child in the same way as if they had been passed the normal way (because, of course, I don't want my child component to have to know whether it received its props through spread of jsx attributes).

**Comment by Deviad** [comment]
Hello everyone,
in relation with what @Aaron-Pool  said, I have asked a question on Stackoverflow a few days ago and I answered my question with almost the same words regarding [the complexity of the passing props, etc. functionally in Vue](https://stackoverflow.com/questions/55006419/vue-js-pass-all-context-when-wrapping-components-with-functional-components/55020805?noredirect=1#comment97832284_55020805). 

However, trying: 
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return <WrappedComponent class="whatever" { ...{ props, listeners } } />;
  }
}
export default Component(Select);
Where Select in my case is the Select component from Element UI produces "props is undefined".


Thank you everyone for your help and time.

**Comment by Aaron-Pool** [comment]
@Deviad I would again recommend a more thorough reading of the vue-jsx docs before you try to dive in on this, or I think you'll find yourself getting frustrated, when things don't work the way you expect. Particularly if you have a background in react. The differences between Vue and React JSX are pretty subtle. For example:

```js
function Component(WrappedComponent) {
  return function(h, {props, listeners}) {
    return <WrappedComponent class="whatever" { ...{ props, listeners } } />;
  }
}
export default Component(Select);
```

The above is not, to my knowledge, a valid functional component. Functional components must be declared either as as full component definition object with the `functional` field set to true, _or_ as a function which conforms to the format prescribed by the `function-components-sugar` transform. Which will transform an _arrow_ function that is either a default export or assigned to an uppercase variable declaration.

Like so:
```js
function Component(WrappedComponent) {
  const HocComponent = ({props, listeners}) => (
    <WrappedComponent class="whatever" { ...{ props, listeners } } />
  );
  return HocComponent;
}
export default Component(Select);
```
