### ISSUE TITLE
The `scopedSlots` can't work properly

### ISSUE THREAD

**Issue by jdz321** [vuejs/jsx#59]
hey..  
我在用vue和elementui，尝试包装一个PopConfirm组件,类似[antd的PopConfirm](https://ant.design/components/popconfirm-cn/), 这是我的demo
[https://github.com/jdz321/vue-jsx-demo](https://github.com/jdz321/vue-jsx-demo)  

components/A.vue 使用render函数和jsx  
components/B.vue 使用普通的template  

B可以正常工作，但是A点击没有反应。 这是我的render函数

```jsx
{
  render() {
    const scopedSlots = {
      reference: () => this.$slots.default,
    }
    return (
      <ElPopover placement="top" width="160" vModel={this.visible} scopedSlots={scopedSlots}>
        {this.$slots.content ? this.$slots.content : (
          <p>{this.content}</p>
        )}
        <div style="text-align: right; margin: 0">
          <ElButton size="mini" type="text" vOn:click={this.onCancelClick}>{this.cancelText}</ElButton>
          <ElButton type="primary" size="mini" vOn:click={this.onOkClick}>{this.okText}</ElButton>
        </div>
      </ElPopover>
    )
  }
}
```

我参考了 [这个PR里的写法](https://github.com/vuejs/jsx/pull/56/commits/54835cce885d76bb0764674901705ba89e6d1121), 这不一定是一个issue，很可能是我的写法不对。

感谢。

**Comment by credred** [comment]
elementui的Popover组件reference是slot而不是scopedSlots，所以你可以尝试这样写：
```jsx
render(h) {
  return (
    <ElPopover placement="top" width="160" vModel={this.visible}>
      {this.$slots.content ? this.$slots.content : (
        <p>{this.content}</p>
      )}
      <div style="text-align: right; margin: 0">
        <ElButton size="mini" type="text" vOn:click={this.onCancelClick}>{this.cancelText}</ElButton>
        <ElButton type="primary" size="mini" vOn:click={this.onOkClick}>{this.okText}</ElButton>
      </div>
      <template slot="reference">{this.$slots.default}</template>
    </ElPopover>
  );
}
```

**Comment by jdz321** [comment]
> elementui的Popover组件reference是slot而不是scopedSlots，所以你可以尝试这样写：
> 
> ```js-jsx
> render(h) {
>   return (
>     <ElPopover placement="top" width="160" vModel={this.visible}>
>       {this.$slots.content ? this.$slots.content : (
>         <p>{this.content}</p>
>       )}
>       <div style="text-align: right; margin: 0">
>         <ElButton size="mini" type="text" vOn:click={this.onCancelClick}>{this.cancelText}</ElButton>
>         <ElButton type="primary" size="mini" vOn:click={this.onOkClick}>{this.okText}</ElButton>
>       </div>
>       <template slot="reference">{this.$slots.default}</template>
>     </ElPopover>
>   );
> }
> ```

奥对咯，感谢。  有点绕哈哈
