### ISSUE TITLE
how to use v-slot in jsx

### ISSUE THREAD

**Issue by Cardier** [vuejs/jsx#61]
return (
   <InputDom config={item}>
        <label slot='default'>{item.placeholder + '1233423'}</label>
        <div slot='foo'>{item.placeholder}</div>
   </InputDom>
)
these two slots  are all in default,why?if i was wrong,then how i can do to fix this?

**Comment by nickmessing** [comment]
Please use [chat](https://chat.vuejs.org/) or [forum](https://forum.vuejs.org/) for questions.
