### ISSUE TITLE
Is it safe to use the `hook` property of the vNode interface?

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/jsx#63]
After poking around the source code a bit, I noticed the `hook` property that can be set on the data object of a vnode, and It actually helped me solve one of the problems I was dealing with in a pretty elegant manner, but, since it's not documented anywhere, I wanted to make sure that that API is stable and ok to use in userland. Is that the case? My assumption is that it mirrors the `hooks` present on a directive.

**Comment by nickmessing** [comment]
@Aaron-Pool, it's never safe to use undocumented features, it's unlikely it's going to change in the 2.x branch but it's possible and will be extremely hard to debug if behaviour changes.
