### ISSUE TITLE
ReferenceError: h is not defined

### ISSUE THREAD

**Issue by dmnrmr** [vuejs/jsx#64]
This code works:
```
<script>
export default {
  name: 'DmFoo',
  functional: true,
  render() {
    return <p>hello</p>;
  }
};
</script>
```

However this does not:
```
<script>
export default {
  name: 'DmFoo',
  functional: true,
  render: () => <p>hello</p>
};
</script>
```

**Comment by Lamberthassel** [comment]
You lose `this` while using arrow functions so `const h = this.$createElement` becomes `undefined` 

More information here: https://github.com/vuejs/babel-plugin-transform-vue-jsx#h-auto-injection

**Comment by dmnrmr** [comment]
I see.
