### ISSUE TITLE
it seems that 「slots」 don't work

### ISSUE THREAD

**Issue by light0x00** [vuejs/jsx#65]
the following is the code  which with the problem.

the child component :

```jsx
export default {
    mounted(){
    },
    render() {
        return <div>
                    Hello,<slot name="default"></slot>
                </div>
    }
}
```

the parent component:

```vue
<template>
       <JsxComp>Slot Word</JsxComp>
</template>
<script>
export default {
  components: { JsxComp }
};
</script>
```

the render result:
```
Hello,
```

> the slots doesn't render anything

here is a repo to reproduce it.

https://github.com/light0x00/vue-jsx-issue.git

**Comment by TerenceZ** [comment]
You should access slots through `this.$scopedSlots.default()`. Because `<slot />` is complied in `.vue` file, but not with JSX.

**Comment by light0x00** [comment]
> You should access slots through `this.$scopedSlots.default()`. Because `<slot />` is complied in `.vue` file, but not with JSX.

thanks,i had resolved it. I misunderstand that the render method does not use the vue-template-compiler, and that the vue-jsx should just convert the tag to VNode via createElement.

**Comment by smalllong** [comment]
> You should access slots through `this.$scopedSlots.default()`. Because `<slot />` is complied in `.vue` file, but not with JSX.

Why not adding `<slot />` support with JSX? I can't use `this.$scopedSlots.default()` in a functional component.

**Comment by webistomin** [comment]
> > You should access slots through `this.$scopedSlots.default()`. Because `<slot />` is complied in `.vue` file, but not with JSX.
> 
> Why not adding `<slot />` support with JSX? I can't use `this.$scopedSlots.default()` in a functional component.

Yes, you can. 

```js
export const Example = (context) => {
  return (
   <div>
    {context.children}
    // or {context.slots().default}
  </div>
  )
}
```
