### ISSUE TITLE
Should move attributes not reserved or prefixed to attrs property in JSXSpreadAttribute

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/jsx#66]
Currently, I wrote a vue-cli-plugin [vue-cli-plugin-tsx](https://github.com/TerenceZ/vue-cli-plugin-tsx) to help writing TSX, but jsx spread attributes not work as expectation (At present, I write a babel plugin to transform JSXSpreadAttributes before vue's jsx to transform). For example, the expression `<Element { ...{ a, b, c, on, slot } } />` will transform to something like `h(Element, {  a, b, c, on, slot })`, so should we move attributes not reserved or prefixed to attrs property in JSXSpreadAttribute?

**Comment by nickmessing** [comment]
Unfortunately there's an issue with spread & TSX because Vue doesn't work like React and TypeScript was heavily build around React's TSX, we are going to solve it in Vue 3. We cannot change it in Vue 2, sorry :(
