### ISSUE TITLE
Functional components type error ts2322

### ISSUE THREAD

**Issue by nicefan** [vuejs/jsx#68]
`<VIf condition={true}>`
> 不能将类型“{ condition: boolean | undefined; }”分配给类型“{ props: any; }”。
>   类型“{ props: any; }”上不存在属性“condition”。ts(2322)

如果改成 `(ctx)=><div>ctx.props.condition</div>` 没问题
这种写法在非jsx中 注册到components中的时候控制台也会报类型错误，但不影响编译

**Comment by haoqunjiang** [comment]
能否提供可以运行的复现？没太懂你的问题

**Comment by nicefan** [comment]
functional component
name.tsx
```
export default ({props})=><div>props.value</div>
```
used.tex
```
import Name from './name'
...
render () {
  return (
    <div><Name value={this.fullname} /></div>
  )
}
...
```
这样`Name` 标签就会报类型错误：

> 不能将类型“{ value: string | undefined; }”分配给类型“{ props: any; }”。
> 类型“{ props: any; }”上不存在属性“value”。ts(2322)

**Comment by haoqunjiang** [comment]
你需要给 props 加上类型声明，这是正常报错。

**Comment by haoqunjiang** [comment]
哦我知道了，你应该是碰上了这个问题 https://github.com/vuejs/vue-cli/issues/2417
请使用 vue-tsx-support https://github.com/wonderful-panda/vue-tsx-support
