### ISSUE TITLE
Data spread operation mutates given object

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/jsx#7]
Hey, I'm leaving this issue here, as well as https://github.com/vuejs/babel-helper-vue-jsx-merge-props/issues/10, because I'm not sure which repository is where bugs will be handled going forward.

I suppose this could be _intended_ behavior, but if it is, I'd kinda wanna know why.

I was writing some stories for my vue storybook and ran into an instance where I was iterating over different variations of a component like so:

```js
render() {
    types = [...blah];
    types.map(t => {
        const data = { attrs: { types[t]: true } };
        <ProfilePic {...data} />
        <ProfilePic url={picUrl} {...data} />
    }
}
```

I was getting odd behavior on the second component, and I managed to track it down to the fact that the `data` object is actually mutated in the creation of the first element. All the props are removed from the `data` object when props are "extracted" and applied to the element.

Is this intended behavior? or a bug? It seems like the data object to be merged should be cloned instead of mutated, but let me know if there's a reason for this. I can create a repro code pen if needed.

**Comment by yyx990803** [comment]
Please provide a reproduction showing more specifically what is being mutated.

**Comment by Aaron-Pool** [comment]
Ok! Here you are: https://codepan.net/gist/8336b69647780baba348ca380c83be59

As you can see, if two elements share a data object, the first jsx element seems to _remove_ the prop field from the data object when it uses it.

**Comment by yyx990803** [comment]
This actually is a behavior in Vue core, where attrs that are extracted as props by the child component are being removed from the hash.

This is indeed a non-optimal implementation (we will keep this in mind for core), but in your case, you should be using `props` instead of `attrs` which works as intended.

**Comment by Aaron-Pool** [comment]
Right, `props` does seem like the better option, now that you mention it. Still seems like there would be instances where you might want to use this technique to iteratively distribute attributes as well as props. But yes, my specifc case is remedied by using `props` instead, so I'm good.
