### ISSUE TITLE
ReferenceError: h is not defined

### ISSUE THREAD

**Issue by MohitTilwani15** [vuejs/jsx#73]
babel.config.js
```
module.exports = {
  presets: [
    '@babel/preset-env',
    '@vue/babel-preset-jsx'
  ],
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
    '@babel/plugin-transform-runtime',
  ],
  comments: false,
  env: {
    test: {
      presets: ['@babel/preset-env'],
      plugins: [
        'babel-plugin-dynamic-import-node',
      ],
    },
  },
};
```

`target` property in `tsconfig` is `esnext`. I also tried `es2015`. Still doesn't work. The file extension is `.tsx`. Please let me know if you more details

**Comment by haoqunjiang** [comment]
What's the file content?
You may also need to set `"jsx": "preserve"` in `tsconfig.json`

**Comment by MohitTilwani15** [comment]
Deleting the node_modules and installing again did the trick. Sorry for late reply. @sodatea Thanks for reply :) Closing the issue
