### ISSUE TITLE
h autoinject does not work on .tsx files

### ISSUE THREAD

**Issue by gettinToasty** [vuejs/jsx#74]
Referencing https://github.com/vuejs/jsx/issues/62 and running into the same issue. h autoinjection performs correctly when applied to a .jsx file extension but not on a .tsx file extension.

**Comment by gettinToasty** [comment]
Closing this issue as I was able to resolve-- if the `target` in tsconfig is set to ES5 the autoinjection script will not function properly as it uses the incompatible `const` declaration.

**Comment by xxbld** [comment]
> Closing this issue as I was able to resolve-- if the `target` in tsconfig is set to ES5 the autoinjection script will not function properly as it uses the incompatible `const` declaration.

@gettinToasty  hi,  how to fix it?

**Comment by WangJiangJiaoZi** [comment]
> > Closing this issue as I was able to resolve-- if the `target` in tsconfig is set to ES5 the autoinjection script will not function properly as it uses the incompatible `const` declaration.
> 
> @gettinToasty hi, how to fix it?

tsconfig:
compilerOptions:{
      target: "esnext"
}
