### ISSUE TITLE
写vOn:click={this.method}直接提示语法错误

### ISSUE THREAD

**Issue by zengyuanqiu** [vuejs/jsx#77]
![image](https://user-images.githubusercontent.com/30031554/63406385-4d81ee80-c41c-11e9-8127-38456e91132e.png)

**Comment by haoqunjiang** [comment]
See https://github.com/vuejs/jsx/issues/52 https://github.com/Microsoft/TypeScript/issues/7411

**Comment by TimYi** [comment]
我也遇到同样的问题，项目中需要在typescript中使用jsx，但是目前这个状态绑定不了事件，进行不下去了。
有没有其它办法支持？比如换回旧版本的jsx语法，项目是使用最新vue-cli创建的。

**Comment by TimYi** [comment]
只能用[spread语法](https://github.com/vuejs/jsx#attributesprops)来写了，满脸黑线。

**Comment by chenjiahan** [comment]
Try this:

```jsx
<div onClick={() => {}} />
```

**Comment by Ttou** [comment]
@chenjiahan 这样写的话，事件修饰符怎么加？

**Comment by chenjiahan** [comment]
修饰符没法加哈，不过 prevent/stop 这种都是一行代码能搞定的

**Comment by TimYi** [comment]
@chenjiahan ```<div onClick={() => {}} />```这是旧版本的语法，最新的vue-cli里好像不好使了，无效。新语法在typescript里又用不了。

**Comment by melunar** [comment]
> @chenjiahan `<div onClick={() => {}} />`这是旧版本的语法，最新的vue-cli里好像不好使了，无效。新语法在typescript里又用不了。

既然是jsx语法 就应该在语法上随从人家，vOn:click的写法太丑了，还有class也不能写成className

**Comment by xmsz** [comment]
> > @chenjiahan `<div onClick={() => {}} />`这是旧版本的语法，最新的vue-cli里好像不好使了，无效。新语法在typescript里又用不了。
> 
> 既然是jsx语法 就应该在语法上随从人家，vOn:click的写法太丑了，还有class也不能写成className

+1

**Comment by TimYi** [comment]
> > @chenjiahan `<div onClick={() => {}} />`这是旧版本的语法，最新的vue-cli里好像不好使了，无效。新语法在typescript里又用不了。
> 
> 既然是jsx语法 就应该在语法上随从人家，vOn:click的写法太丑了，还有class也不能写成className

关键是两种都用不了，得用最麻烦的spread语法（手动捂脸）

**Comment by Xinayu** [comment]
try `vOn:click={this.method.bind(this)}`

**Comment by TimYi** [comment]
@Xinayu 在typescript环境里无法使用vOn:click

**Comment by xuanhen2013** [comment]
@TimYi 使用 on={{click: func}}

**Comment by harvey-woo** [comment]
> @chenjiahan 这样写的话，事件修饰符怎么加？
```typescript
// jsx-utils.ts
import { L } from 'ts-toolbelt';

export const keys = <{ <T>(o: NonNullable<T>): Array<keyof T> }>Object.keys;

type Decorators = { stop: boolean, prevent: boolean, self: boolean };
const defaultDecorators: Decorators = {
  stop: false,
  prevent: false,
  self: false,
};
type Handler = (this: any, event: Event, ...args: any[]) => any;
type HandlerWrapper<F extends Handler> = {
  (handler?: F): (this: ThisType<F>, event: Parameters<F>[0], ...args: L.Tail<Parameters<F>>)
   => ReturnType<F>
} & { [k in keyof Decorators]: HandlerWrapper<F> } & {
  handler: (event: Parameters<F>[0]) => void
};

const generateWrapper = <F extends Handler>(params: Partial<Decorators>) => {
  const { stop, prevent, self } = params;
  const wrapper = ((fn?: F) => {
    return function handler(event, ...args) {
      if (prevent) {
        event.preventDefault();
      }
      if (stop) {
        event.stopPropagation();
      }
      if (fn && (!self || event.target === event.currentTarget)) {
        return fn.call(this, event, ...args);
      }
      return undefined;
    };
  }) as HandlerWrapper<F>;
  keys(defaultDecorators).forEach((k) => {
    if (!(k in params)) {
      wrapper[k] = generateWrapper({ ...params, [k]: true });
    }
  });
  wrapper.handler = (event) => {
    if (prevent) {
      event.preventDefault();
    }
    if (stop) {
      event.stopPropagation();
    }
  };
  return wrapper;
};

export const stop = generateWrapper({ stop: true });
export const prevent = generateWrapper({ prevent: true });
export const self = generateWrapper({ self: true });
```

```tsx
import { stop, prevent, self } from './jsx-utils'

export default {
    // 使用 prevent，self，stop，三个方法
    // 或者直接返回 prevent.handler, stop.handler
    // 也可以 prevent.stop 这样链式使用
    render() {
        return <div 
            onClick={prevent.handler} 
            onMousedown={prevent.stop.self(() => { console.log('HelloWorld')})} />
    }
}
```

**Comment by DUAN930909** [comment]
on-click={ this.fun }

**Comment by wjkang** [comment]
> @chenjiahan `<div onClick={() => {}} />`这是旧版本的语法，最新的vue-cli里好像不好使了，无效。新语法在typescript里又用不了。

新vue-cli创建的项目跟旧的创建的项目，用的是同一个版本的@vue/babel-preset-jsx，是vue-cli干了什么吗？好恶心人啊

**Comment by mikepxq** [comment]
尽然 tsx 维护起来这么难
vue官方 就直接说不用 tsx的呢
免得，三方库也是遇到各种问题
vue底层也要做兼容的代码

**Comment by galenjiang** [comment]
一言难尽，为了类型才用的jsx写法，必然配合要用tsx。只能说修饰符看起来美好，其实是画蛇添足。

**Comment by haoqunjiang** [comment]
TS 4.2 已经支持此语法。请自行升级项目中的 TypeScript 版本。

**Comment by galenjiang** [comment]
还有一个edge case没有考虑到，例如 emit('update:someValue'), 
`<SomeComponent vOn:update:someValue={callback} />`
这时候编译不过。

**Comment by chenjiahan** [comment]
@galenjiang 最新版 TS 已经支持冒号了

**Comment by galenjiang** [comment]
> @galenjiang 最新版 TS 已经支持冒号了

是两个冒号不是一个冒号
而且ts修复的是namespace, 但是vue奇怪的事件系统只是看起来像,但事实并不是。

**Comment by chenjiahan** [comment]
两个冒号没有必要把？ 直接 `onUpdate:xxx` 就可以

**Comment by galenjiang** [comment]
> 两个冒号没有必要把？ 直接 `onUpdate:xxx` 就可以

没效果，不触发事件。
