### ISSUE TITLE
Report BUG of vModel

### ISSUE THREAD

**Issue by Veath** [vuejs/jsx#79]
```
<input vModel={data.value} />
```
is working ↑↑

but:
```
<input vModel={data['value']} />
```
error!!!!

**Comment by haoqunjiang** [comment]
What error? Could you please provide a detailed reproduction for this issue so that we can investigate on?

**Comment by Veath** [comment]
i use function wraps jsx causing this to be lost.
```js
<input vModel={data['value']} />

// vue bable jsx transfrom v-model (data['value']) to-->
 this.$set(data, value, xxxx)
```
so use the arrow function instead
