### ISSUE TITLE
Package requires deprecated babel dependency.

### ISSUE THREAD

**Issue by Sebi2020** [vuejs/jsx#82]
The jsx preset should depend on babel-cli which is the successor of the babel package:

**NPM output**:
> ```npm
> npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of > babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
> ```

**Comment by haoqunjiang** [comment]
I'm sorry but I really don't see any reference to the babel@6 dependency in this repository.
