### ISSUE TITLE
Replace JSXElement node on 'exit' instead of 'enter'.

### ISSUE THREAD

**Issue by nandin-borjigin** [vuejs/jsx#86]
Current [behavior] of this plugin is replacing the entire JSXElement node, along with its children, on `enter` phase, which hinders other plugins from visiting decendants of that JSXElement recursively.

## Usecase:
Suppose that a plugin `foo` is to collect thrid party component references in every file and then emit a file that imports and globally registeres all used components (common practice when the third party library provides tons of components but only a few of them is of interest). 

## Problem: 
With this (referring to @vue/babel-plugin-transform-vue-jsx) plugin applied, `foo` can only visit the root JSXElement and all of its children would not be visited because they would have been replaced with normal `h` call by this plugin. Indeed, author of `foo` can traverse the children of root JSXElement by himself/herself but that would be duplicating the visitor pattern provided by babel. 

## Solution:
Changing this plugin's visitor to replace the original jsx node on `exit` phase would make other plugins (which are, by assumption, applied prior to this plugin) have a chance to recursively visit all the jsx nodes, without affecting the original behavior of this plugin.

## Reference:
Both [babel-plugin-jsx] and [babel-plugin-transform-react-jsx](which inherits the former) are applying the actual transformation on `exit` phase.

[behavior]: https://github.com/vuejs/jsx/blob/67d6d39beab9f853118b4e0bbe901f5899ae7245/packages/babel-plugin-transform-vue-jsx/src/index.js#L455
[babel-plugin-jsx]: https://github.com/OpenJSX/babel-plugin-jsx
[babel-plugin-transform-react-jsx]: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/README.md

**Comment by nickmessing** [comment]
Good point, Vue had a lot of updates that are currently not supported entirely by JSX, I'm working on a changelist to update JSX and will include this too.
