### ISSUE TITLE
配置之后仍然不能解析vue文件中的jsx

### ISSUE THREAD

**Issue by zln777** [vuejs/jsx#92]
![image](https://user-images.githubusercontent.com/49901592/70976182-77a39e80-20e6-11ea-901b-1f35e19d4df1.png)
照着文档下载并配置之后仍然报错
![image](https://user-images.githubusercontent.com/49901592/70976236-92761300-20e6-11ea-9e95-7c090fa78cda.png)
请问有人知道是什么原因吗

**Comment by huaganshang** [comment]
me too

**Comment by haoqunjiang** [comment]
从报错来看应该是因为你没有配置 babel-loader
